spring:
  application:
    name: personal-ai-os

  datasource:
    url: jdbc:postgresql://localhost:5432/personal_ai_os
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false


  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      chat:
        model: openrouter/free

    model:
      audio:
        speech: none
        transcription: none

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info